server:
  port: 8087
spring:
  application:
    name: every-upload
  servlet:
    multipart:
      max-file-size: 5MB # 限制文件上传的大小
  datasource:
    url: jdbc:mysql://192.168.109.201:3306/leyou?useSSL=false&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    hikari:
      max-lifetime: 28830000 # 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒，参考MySQL wait_timeout参数（show variables like '%timeout%';）
      maximum-pool-size: 9 # 连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
#  redis:
#    host: 192.168.109.102
#  rabbitmq:
#      host: 192.168.109.102
#      username: leyou
#      password: leyou
#      virtual-host: /leyou
#      publisher-confirms: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
#      defaultZone: http://192.168.109.201:10086/eureka

  instance:
    lease-renewal-interval-in-seconds: 5 # 5秒钟发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期

fdfs:
  so-timeout: 1501 # 超时时间
  connect-timeout: 601 # 连接超时时间
  thumb-image: # 缩略图
    width: 60
    height: 60
  tracker-list: # tracker地址：你的虚拟机服务器地址+端口（默认是22122）
    - 192.168.109.201:22122

mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
logging:
  level:
    com.lxd.mapper: debug