server:
  port: 6767
spring:
  application:
    name: every-h5
  datasource:
    url: jdbc:mysql://192.168.109.201:3306/leyou
    username: root
    password: 123456
    hikari:
      max-lifetime: 28830000 # 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒，参考MySQL wait_timeout参数（show variables like '%timeout%';）
      maximum-pool-size: 9 # 连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
  redis:
    host: 192.168.109.102
  rabbitmq:
    host: 192.168.109.102
    username: leyou
    password: leyou
    virtual-host: /leyou
    publisher-confirms: true
    listener:
      simple:
        default-requeue-rejected: false

mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
logging:
  level:
    com.lxd.mapper: debug
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  #      defaultZone: http://192.168.109.201:10086/eureka

  instance:
    lease-renewal-interval-in-seconds: 5 # 5秒钟发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期

leyou:
  jwt:
    secret: leyou@Login(Auth}*^31)&heiMa% # 登录校验的密钥
    pubKeyPath: F:\\tmp\\rsa\\rsa.pub # 公钥地址
    priKeyPath: F:\\tmp\\rsa\\rsa.pri # 私钥地址
    expire: 30 # 过期时间,单位分钟
    cookieName: COOKNA
    cookieMaxAge: 30
